### ISSUE TITLE
Access API to get json formatted data

### ISSUE THREAD

**Issue by Piashsarker** [shahariaazam/DSE-Share-Market-Update#2]
Web URL is not working .
![image](https://cloud.githubusercontent.com/assets/8473499/24185846/7d131e5a-0eff-11e7-9330-93e90682ec9d.png)

**Comment by Darahat** [comment]
I also trying to get json data using this url but it does not work..

**Comment by mhabid98** [comment]
I also trying to get JSON data using this URL but it does not work.

**Comment by shahariaazam** [comment]
@mhabid98 that JSON data api was hosted in a free AWS account that we are not maintaining anymore. But very soon, I am going to publish a public API for this. Most probably on GAE.
Thanks.
