### ISSUE TITLE
Possible to make one for Chittagong Stock Exchange?

### ISSUE THREAD

**Issue by simongomes** [shahariaazam/DSE-Share-Market-Update#3]
The api is working just fine. But is it possible to make some functionality so that it works with Chittagong Stock Exchange? Thanks in advance.

**Comment by shahariaazam** [comment]
@gomessimon thanks for your suggestions. I have a plan to do that soon.

**Comment by shahariaazam** [comment]
I have added the functionality to get data from Chittagong Stock Exchange too. Please check it out our latest release from [here](https://github.com/shahariaazam/DSE-Share-Market-Update/releases).
