### ISSUE TITLE
Library is not working now.

### ISSUE THREAD

**Issue by gomessimon** [shahariaazam/DSE-Share-Market-Update#6]
After following the instruction from your git repo this is not working now. The old one works by the way. 

What I did was:

1. Installed it using composer 
`composer require shahariaazam/bd-stock-exchange`
2. Added the following into my index.php
```<?php
require "vendor/autoload.php";

$dse = new \Shaharia\BDStockExchange\StockPrice();
var_dump($dse->getDSEPricing());
```
Giving me error:
`Fatal error: Uncaught Error: Class 'Shaharia\BDStockExchange\StockPrice' not found in G:\xampp\htdocs\dse\index.php:6 Stack trace: #0 {main} thrown in G:\xampp\htdocs\dse\index.php on line 6`

My folder structure:
```
- vendor
- composer.json
- composer.lock
- index.php
```

**Comment by gomessimon** [comment]
Not working bro, getting this now.

```
Warning: file_get_contents(): stream does not support seeking in G:\xampp\htdocs\dse\vendor\sunra\php-simple-html-dom-parser\Src\Sunra\PhpSimple\simplehtmldom_1_5\simple_html_dom.php on line 81

Warning: file_get_contents(): Failed to seek to position -1 in the stream in G:\xampp\htdocs\dse\vendor\sunra\php-simple-html-dom-parser\Src\Sunra\PhpSimple\simplehtmldom_1_5\simple_html_dom.php on line 81

Notice: Undefined variable: array in G:\xampp\htdocs\dse\vendor\shahariaazam\bd-stock-exchange\src\StockPrice\DSE.php on line 38
NULL
```

**Comment by shahariaazam** [comment]
@gomessimon it can be any network related issues.

Run the following code and paste the output here.

```php
<?php
$dse = file_get_contents("https://www.dsebd.org")
print_r($dse);
```

And also tell me which PHP version are you using. Because this seems working fine from my end. You need to give me details information to look at.

**Comment by shahariaazam** [comment]
@gomessimon it's OK now?
